"""empty message

Revision ID: 5c9c646f46ad
Revises: 109f78406230
Create Date: 2018-04-07 22:47:07.341917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9c646f46ad'
down_revision = '109f78406230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applycard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('limit', sa.String(length=100), nullable=False),
    sa.Column('idcard', sa.String(length=24), nullable=False),
    sa.Column('phone', sa.String(length=110), nullable=True),
    sa.Column('email', sa.String(length=24), nullable=False),
    sa.Column('address', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['phone'], ['user.phone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applycard')
    # ### end Alembic commands ###
