"""empty message

Revision ID: aff398ef8896
Revises: b127157482e5
Create Date: 2018-04-09 18:42:33.664781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff398ef8896'
down_revision = 'b127157482e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consume', sa.Column('Ctype', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consume', 'Ctype')
    # ### end Alembic commands ###
