"""empty message

Revision ID: b127157482e5
Revises: 5c9c646f46ad
Create Date: 2018-04-08 15:31:29.640644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b127157482e5'
down_revision = '5c9c646f46ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit', sa.Column('email', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit', 'email')
    # ### end Alembic commands ###
