"""empty message

Revision ID: c4da673beb3e
Revises: 
Create Date: 2018-04-05 11:29:29.567812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4da673beb3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=30), nullable=False),
    sa.Column('limit', sa.String(length=20), nullable=False),
    sa.Column('overMoney', sa.String(length=20), nullable=False),
    sa.Column('creditName', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('vailDate', sa.DateTime(), nullable=True),
    sa.Column('cdt_status', sa.SmallInteger(), nullable=False),
    sa.Column('idCard', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['phone'], ['user.phone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_id')
    )
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('job', sa.String(length=10), nullable=False),
    sa.Column('idCard', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['phone'], ['user.phone'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idCard')
    )
    op.create_table('consume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=30), nullable=True),
    sa.Column('consume_date', sa.DateTime(), nullable=False),
    sa.Column('sum_money', sa.DECIMAL(precision=12, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.credit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=30), nullable=True),
    sa.Column('sum_money', sa.DECIMAL(precision=12, scale=1), nullable=False),
    sa.Column('deal_date', sa.DateTime(), nullable=False),
    sa.Column('deal_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.credit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_id', sa.String(length=30), nullable=True),
    sa.Column('debt_date', sa.DateTime(), nullable=False),
    sa.Column('sum_money', sa.DECIMAL(precision=12, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['credit_id'], ['credit.credit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debt')
    op.drop_table('deal')
    op.drop_table('consume')
    op.drop_table('info')
    op.drop_table('credit')
    op.drop_table('user')
    op.drop_table('admin')
    # ### end Alembic commands ###
